-- public.todos
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  task text not null,
  status text default 'Not Started',
  user_id uuid not null references auth.users(id) on delete cascade,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.todos enable row level security;
create policy "todos read own"   on public.todos for select using (auth.uid() = user_id);
create policy "todos insert own" on public.todos for insert with check (auth.uid() = user_id);
create policy "todos update own" on public.todos for update using (auth.uid() = user_id);
create policy "todos delete own" on public.todos for delete using (auth.uid() = user_id);
