name: ci

on:
  pull_request:
    branches: [main, develop]
  push:
    branches:
      - 'feature/*'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint -- --format junit --output-file lint-report.xml
      - run: pnpm typecheck
      - run: pnpm doctor
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: lint-report.xml
