name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # твоя версия из `flutter doctor`
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # Если есть codegen (build_runner), раскомментируй:
      # - name: Run build_runner
      #   run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --no-pub
